### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to TChat v4.2.3

### ISSUE THREAD

**Issue by EHCanadian** [TectHost/TChat#14]
CraftBukkit version 4343-Spigot-a759b62-0a7bd6c (MC: 1.21.1)

any insight as to what is going on...

tchat v4.2.3 spigotmc

`[17:13:23] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TChat v4.2.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2026) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4343-Spigot-a759b62-0a7bd6c]
	at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2148) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4343-Spigot-a759b62-0a7bd6c]
	at net.minecraft.server.network.PlayerConnection.lambda$handleChat$5(PlayerConnection.java:1804) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4343-Spigot-a759b62-0a7bd6c]
	at net.minecraft.util.FutureChain.a(SourceFile:30) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4343-Spigot-a759b62-0a7bd6c]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "config.WorldsManager$WorldConfigData.bpNone()" because "worldConfigData" is null
	at listeners.ChatFormatListener.playerFormat(ChatFormatListener.java:87) ~[?:?]
	at listeners.ChatListener.onPlayerChat(ChatListener.java:60) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	... 12 more
[17:13:23] [Async Chat Thread - #0/INFO]: <[0;31;22mEHCanadian83[m> t[m`

**Comment by EHCanadian** [comment]
Okies, TChat\worlds.yml needs to be edited and rename

world_the_end
world_nether
world

to your minecraft world folder name. (example)
mc_the_end
mc_nether
mc
