### ISSUE TITLE
Error when plugin is starting

### ISSUE THREAD

**Issue by Cr4zyGeek** [TectHost/TChat#15]
Hi, the plugin stops when the server starts

Plugin version : 4.3.0.0
Server version : paper 1.20.6

```
[20:56:58 ERROR]: Error occurred while enabling TChat v4.3.0.0 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be Methodref constant
        at TChat-4.3.0.0.jar/utils.ChatGamesSender.showEffects(ChatGamesSender.java:137) ~[TChat-4.3.0.0.jar:?]
        at TChat-4.3.0.0.jar/utils.ChatGamesSender.showStartEffects(ChatGamesSender.java:96) ~[TChat-4.3.0.0.jar:?]
        at TChat-4.3.0.0.jar/utils.ChatGamesSender.startNextGame(ChatGamesSender.java:54) ~[TChat-4.3.0.0.jar:?]
        at TChat-4.3.0.0.jar/utils.ChatGamesSender.<init>(ChatGamesSender.java:28) ~[TChat-4.3.0.0.jar:?]
        at TChat-4.3.0.0.jar/minealex.tchat.TChat.registerChatGames(TChat.java:438) ~[TChat-4.3.0.0.jar:?]
        at TChat-4.3.0.0.jar/minealex.tchat.TChat.registers(TChat.java:165) ~[TChat-4.3.0.0.jar:?]
        at TChat-4.3.0.0.jar/minealex.tchat.TChat.onEnable(TChat.java:96) ~[TChat-4.3.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Tect-host** [comment]
Disable sounds in the chatgames.yml file

**Comment by Nodek1984** [comment]
Why you don't disable them in the plugin jar ? Not possible that users download the plugin and it don't even starts because things don't work you add into
