### ISSUE TITLE
ERROR WHEN /R, /BC, /TELL, /WHISPER, /CC, /PM

### ISSUE THREAD

**Issue by HonzasikCZ** [TectHost/TChat#4]
I tried the commands and I noticed that these commands don't work...it shows an error in the console and no functionality
I have already removed some commands from the commands.yml file so I have no idea what other commands might not work but it looks like these are all that worked as shortcuts for other commands
**ERROR:**
```
[21:41:34 INFO]: honzas123 issued server command: /r
[21:41:34 ERROR]: Could not pass event PlayerCommandPreprocessEvent to TChat v4.0.3
java.lang.StringIndexOutOfBoundsException: Range [1, 0) out of bounds for length 0
	at jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
	at jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
	at jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
	at jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
	at jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
	at java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
	at java.lang.String.substring(String.java:2834) ~[?:?]
	at java.lang.String.substring(String.java:2807) ~[?:?]
	at utils.CustomCommands.executeAction(CustomCommands.java:218) ~[TChat.jar:?]
	at utils.CustomCommands.processActions(CustomCommands.java:122) ~[TChat.jar:?]
	at utils.CustomCommands.onPlayerCommand(CustomCommands.java:74) ~[TChat.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor75.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:git-Pufferfish-52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2207) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2191) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Tect-host** [comment]
Yes, in the commands.yml you can modify the aliases of certain commands or create new aliases, send me the commands.yml to check this error.

**Comment by HonzasikCZ** [comment]
```
# #################################################################
# ┌─────────────────────────────────────────────────────────────┐ #
# │                       Custom Commands                       │ #
# └─────────────────────────────────────────────────────────────┘ #
# #################################################################

# Also try LogicalChat! https://www.spigotmc.org/resources/logicalchat-1-20x-best-chat-plugin.114302/

# Tags:
# [MESSAGE] - Sends a message | - "[MESSAGE] &7Test message"
# [TITLE] - Sends a title | - "[TITLE] &aTitle;&bSubtitle"
# [PLAYER_COMMAND] - The player will automatically execute a command | - "[PLAYER_COMMAND] spawn {player}"
# [CONSOLE_COMMAND] - The console will automatically execute a command | - "[CONSOLE_COMMAND] give {player} diamond 1"
# [SOUND] - Executes a sound | - "[SOUND] AMBIENT_CRIMSON_FOREST_MOOD"
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# [PARTICLE] - Executes a particle | - "[PARTICLE] CHERRY_LEAVES"
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# [TELEPORT] - Teleports the player to concrete coordinate | - "[TELEPORT] world;0;70;0"
# [ACTION_BAR] - Executes an action bar | - "[ACTION_BAR] &eWelcome! Have a great time!"
# [INVENTORY] - Adds/removes/changes the inventory of the player | - "[INVENTORY] ADD DIAMOND_SWORD 1" | - "[INVENTORY] REMOVE STONE_SWORD 1" | - "[INVENTORY] CHANGE DIAMOND_SWORD 1 APPLE 1"
# [POTION_EFFECT] - Adds/removes potion effects to the player | - "[POTION_EFFECT] ADD SPEED:120:1" | - "[POTION_EFFECT] REMOVE SPEED"
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
# [BUNGEECORD] - Moves the player to another server | - "[BUNGEECORD] survival"
# [CLICK_ACTION] (action) (executor) | (message) - Message with Text Component | - "[CLICK_ACTION] OPEN https://tect.host/ | Click here to go to tect.host"
# [CLICK_ACTION] OPEN/SUGGEST/EXECUTE
# Conditionals
  # [IF] - Initiates a conditional within the actions | - "[IF] %player_is_op% == true"
    # (ADD) You can use && to add conditions to the if: - "[IF] %statistic_hours_played% >= 10 && %player_is_op% == yes"
    # (OR) You can use || to compare another condition if one of them is not met: - "[IF] %statistic_hours_played% >= 10 && %player_is_op% == yes"
  # [ELSE IF] - If the [IF] condition is not met, it will test this condition | - "[ELSE IF] %player_ping% <= 100"
    # (ADD) You can use && to add conditions to the if: - "[IF] %statistic_hours_played% >= 10 && %player_is_op% == yes"
    # (OR) You can use || to compare another condition if one of them is not met: - "[IF] %statistic_hours_played% >= 10 && %player_is_op% == yes"
  # [ELSE] - If none of the conditions ([IF] and all the [ELSE IF] if any) are not met, this will be executed | - "[ELSE]"
  # [FI] - The condition ends, from this tag, the rest is out of this condition | - "[FI]

commands:
  bc:
    permission-required: false
    args: true
    cooldown: 0
    actions:
      - "[PLAYER_COMMAND] broadcast %args%"
  web:
    permission-required: false
    cooldown: 0
    actions:
      - "[MESSAGE] &8&l[&#084CFB&lWEB&8&l] &#00DFFFidk"
  website:
    permission-required: false
    cooldown: 0
    actions:
      - "[MESSAGE] &8&l[&#084CFB&lWEB&8&l] &#00DFFFidk"
  tt:
    permission-required: false
    cooldown: 0
    actions:
      - "[MESSAGE] &8&l[&#ff0050&lTIKTOK&8&l] &#00f2eaidk"
  tiktok:
    permission-required: false
    cooldown: 0
    actions:
      - "[MESSAGE] &8&l[&#ff0050&lTIKTOK&8&l] &#00f2eaidk"
  instagram:
    permission-required: false
    cooldown: 0
    actions:
      - "[MESSAGE] &8&l[&#833ab4&lINSTAGRAM&8&l] &#c13584idk"
  ig:
    permission-required: false
    cooldown: 0
    actions:
      - "[MESSAGE] &8&l[&#833ab4&lINSTAGRAM&8&l] &#c13584idk"
  dc:
    permission-required: false
    cooldown: 0
    actions:
      - "[MESSAGE] &8&l[&#002bff&lDISCORD&8&l] &#7785ccidk"
  discord:
    permission-required: false
    cooldown: 0
    actions:
      - "[MESSAGE] &8&l[&#002bff&lDISCORD&8&l] &#7785ccidk"
  r:
    permission-required: false
    args: true
    cooldown: 0
    actions:
      - "[PLAYER_COMMAND] reply %args%"
  tell:
    permission-required: false
    args: true
    cooldown: 0
    actions:
      - "[PLAYER_COMMAND] msg %args%"
  whisper:
    permission-required: false
    args: true
    cooldown: 0
    actions:
      - "[PLAYER_COMMAND] msg %args%"
  pm:
    permission-required: false
    args: true
    cooldown: 0
    actions:
      - "[PLAYER_COMMAND] msg %args%"
  cc:
    permission-required: false
    cooldown: 0
    actions:
      - "[PLAYER_COMMAND] clearchat"
```

**Comment by Tect-host** [comment]
On my test server it works, it may be a version issue, to check well, use 1.21 please.

**Comment by HonzasikCZ** [comment]
**1.21:**
```
[21:33:47 ERROR]: Could not pass event PlayerCommandPreprocessEvent to TChat v4.0.3
java.lang.StringIndexOutOfBoundsException: Range [1, 0) out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914) ~[?:?]
	at java.base/java.lang.String.substring(String.java:2876) ~[?:?]
	at java.base/java.lang.String.substring(String.java:2849) ~[?:?]
	at TChat.jar/utils.CustomCommands.executeAction(CustomCommands.java:218) ~[TChat.jar:?]
	at TChat.jar/utils.CustomCommands.processActions(CustomCommands.java:122) ~[TChat.jar:?]
	at TChat.jar/utils.CustomCommands.onPlayerCommand(CustomCommands.java:74) ~[TChat.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor73.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[pufferfish-api-1.21-R0.1-SNAPSHOT.jar:1.21-6-bdb56f1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2135) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2122) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1544) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1521) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1514) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1473) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1480) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1325) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[pufferfish-1.21.jar:1.21-6-bdb56f1]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by Tect-host** [comment]
What command are you executing exactly?

**Comment by HonzasikCZ** [comment]
/r, /bc, /tell /whisper, /cc and /pm

**Comment by Tect-host** [comment]
Without arguments?

**Comment by HonzasikCZ** [comment]
Yes and now I noticed that when I add it to /r it works

**Comment by HonzasikCZ** [comment]
oh and other commands too /tell...

**Comment by HonzasikCZ** [comment]
without error too but /cc still doesn't work at all

**Comment by Tect-host** [comment]
Same error?

**Comment by HonzasikCZ** [comment]
For /cc it doesn't even write an error to the console only in game this:
![obrazek](https://github.com/user-attachments/assets/e57505ca-8b6b-429b-b515-861757c01534)

**Comment by Tect-host** [comment]
Do you have op and a permissions plugin?

**Comment by HonzasikCZ** [comment]
I use Luckperms where op is disabled in the configuration but I have *

**Comment by Tect-host** [comment]
Can you use the /chatclear command?
If not, try /chat clear

**Comment by HonzasikCZ** [comment]
Now I noticed that the /clearchat command doesn't even work normally but there is /chatclear and in commands.yml there is a /clearchat command so that's why it doesn't work...after correction it works correctly
Yes /chatclear is working

**Comment by HonzasikCZ** [comment]
So /cc now works normally and as for the rest, they work with arguments but without them the commands don't work and an error is sent to the console

**Comment by Tect-host** [comment]
Ok, I will add a message to avoid that error, thanks for your report!
